DiscussionPost and Comment endpoints
bounswe/bounswe2022group7 pull request #440
Opened 2022-11-20 21:01 UTC by askabderon

I implemented the endpoints from [the issue](https://github.com/bounswe/bounswe2022group7/issues/438). These endpoints from the future week's tasks and I thought discussing its design beforehand may facilitates the FrontEnd and Mobile team's work.

Get endpoints are pretty straightforward and implemented according to the [meeting notes](https://github.com/bounswe/bounswe2022group7/wiki/CMPE451-Meeting-Notes-%236)

There are two POST endpoints, one for Comment and one for DiscussionPost

1. DiscussionPost:
```json
{
  "title": "string",
  "textBody": "string",
  "posterId": 0
}
```
2. Comment:
```json
{
  "text": "string",
  "commentedObjectId": 0
}
```

Please review and inform me about any changes request about the structures @CahidArda @atillaturkmen. If we agree on the structure, then we can merge it after review @demet47

2022-11-20 21:45 UTC, CahidArda commented
I looked at the CommentService.kt file and saw that you check if the id we provide you belongs to a art item, event or a discussion post. Do you guarantee that there won't be an art item, event or discussion post with the same id?

2022-11-21 07:40 UTC, askabderon commented
> I looked at the CommentService.kt file and saw that you check if the id we provide you belongs to a art item, event or a discussion post. Do you guarantee that there won't be an art item, event or discussion post with the same id?

Yes, they all have different id's then each other.

2022-11-21 07:43 UTC, CahidArda approved these changes

2022-11-21 08:26 UTC, atillaturkmen approved these changes

2022-11-21 16:09 UTC, CahidArda requested changes

2022-11-21 16:09 UTC, CahidArda commented on backend/src/main/kotlin/com/group7/artshare/controller/CommentController.kt
> +            "Id is not match with any of the discussion posts in the database"
Grammer error

2022-11-21 16:09 UTC, CahidArda commented on backend/src/main/kotlin/com/group7/artshare/controller/DiscussionPostController.kt
> +        throw ResponseStatusException(HttpStatus.NOT_FOUND, "Id is not match with any of the discussion posts in the database")
Grammer error

2022-11-21 16:18 UTC, askabderon commented on backend/src/main/kotlin/com/group7/artshare/controller/CommentController.kt
> +            "Id is not match with any of the discussion posts in the database"
fixed with latest commit

2022-11-21 16:18 UTC, askabderon commented on backend/src/main/kotlin/com/group7/artshare/controller/DiscussionPostController.kt
> +        throw ResponseStatusException(HttpStatus.NOT_FOUND, "Id is not match with any of the discussion posts in the database")
fixed with latest commit

2022-11-21 16:22 UTC, askabderon commented
I tried to implement 2 additional endpoints, DELETE comment and DELETE discussion post.

DELETE comment is finished and working as expected. However, it requires a request body as below:
```json
{
    "commentedObjectId":23
}
```
Hence, I am requesting your review about using this endpoint on frontend and mobile. @CahidArda @atillaturkmen 

DELETE discussion post has some issues related to associations of database. I am suspending its implementation since it is not included on the milestone plan and not making longer for waiting this PR's endpoints.

2022-11-21 16:24 UTC, CahidArda approved these changes
I haven't tested the endpoints localy but the endpoint configuration is okay for me.

2022-11-21 19:45 UTC, merged

2022-11-21 19:45 UTC, demet47 commented
I reviewed the code, no peculiarity found.
I also ran the code on my local and tried edge cases, sequential sceniario etc. and couldn't find anything going wrong. Thus I am merging the branch

2022-11-21 19:47 UTC, demet47 reviewed
I reviewed the code, no peculiarity found.
I also ran the code on my local and tried edge cases, sequential sceniario etc. and couldn't find anything going wrong. Thus I am merging the branch

2022-11-21 19:53 UTC, demet47 commented on backend/src/main/kotlin/com/group7/artshare/controller/DiscussionForumController.kt
> +    fun getRecommendedEventsGeneric(): List<DiscussionPost> {
The naming of the method had better be changed in case it is tested in unittest and also for readibility